version: "3.9"

services:
  bot:
    container_name: dao-bot
    image: dao-bot
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ".secret:/app/.secret:ro"
      - ".env:/app/.env:ro"